version: '3'
services:
  server:
    image: nazrin
    build: .
    links:
      - db
    restart: always
    environment:
      NODE_ENV: production
      PORT: 3000
      WAIT_HOSTS: db:27017
    ports:
      - 3000:3000
  db:
    image: mongo
    volumes:
      - ./data:/data/db
