version: '3'
services:
  server:
    image: nazrin
    build: .
    links:
      - db
    restart: always
    environment:
      - NODE_ENV=development
      - PORT=3000
    expose:
      - 3000
  client:
    image: nazrin_client
    build: client
    links:
      - server
    restart: always
    environment:
      - NODE_ENV=development
    ports:
      - 5000:5000
  db:
    image: mongo
    expose:
      - 27017
    volumes:
      - ./data:/data/db
